# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [62]:
import os
import numpy as np
import pandas as pd
import glob

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [5]:
num=[n for n in range(1,51)]
print(num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [6]:
even=[n for n in range(1,201) if n%2==0]
print(even)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [8]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [17]:

        

X = [num for e in a for num in e]
print(x)

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [19]:
c = [num for e in a for num in e if num>=0.5]
print(c)

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]

### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [48]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])
b.size

30

In [55]:
d = [[lista for lista in b.tolist()] for numero in lista]
'''for lista1 in b:
    for listas in lista1:
        for numero in listas:
            d.append(numero)'''

            
        
            
print(d)

NameError: name 'lista' is not defined

### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [71]:
files = [file for file in glob.glob("../data/*.csv")]

print(files)

['../data/sample_file_1.csv', '../data/sample_file_0.csv', '../data/sample_file_2.csv', '../data/sample_file_3.csv', '../data/sample_file_7.csv', '../data/sample_file_6.csv', '../data/sample_file_4.csv', '../data/sample_file_5.csv', '../data/sample_file_8.csv', '../data/sample_file_9.csv']

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [83]:

df = pd.concat([pd.read_csv(file) for file in files])
display(df.head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.276827,0.260054,0.942397,0.113187,0.781355,0.475740,0.152061,0.250324,0.147078,0.162984,0.977025,0.509619,0.593212,0.911839,0.257645,0.386457,0.696932,0.069162,0.952291,0.286542
1,0.995885,0.158381,0.244274,0.962163,0.651900,0.930665,0.577190,0.087914,0.960261,0.580840,0.194616,0.661459,0.674085,0.049326,0.785803,0.315645,0.495355,0.232135,0.549324,0.572232
2,0.641917,0.821055,0.392437,0.782617,0.510762,0.428320,0.017324,0.680720,0.340412,0.462513,0.785776,0.251949,0.032847,0.995700,0.816563,0.735692,0.435998,0.430411,0.531757,0.489528
3,0.806532,0.569258,0.148175,0.809987,0.459632,0.735762,0.730664,0.934502,0.080322,0.763502,0.398504,0.027637,0.409665,0.942846,0.133256,0.157158,0.929446,0.402791,0.685976,0.246594
4,0.311185,0.501165,0.365979,0.782807,0.776795,0.797199,0.791946,0.847157,0.771811,0.233944,0.522344,0.053030,0.208551,0.824354,0.588567,0.604341,0.232964,0.229109,0.022881,0.479022
0,0.734751,0.195362,0.734309,0.598184,0.763433,0.263434,0.868066,0.058092,0.753502,0.587513,0.311608,0.178356,0.182922,0.147631,0.391188,0.816049,0.749068,0.293260,0.937828,0.880858
1,0.772607,0.445391,0.249642,0.787922,0.598583,0.827238,0.624126,0.601524,0.688753,0.338870,0.081595,0.471474,0.267443,0.453351,0.800716,0.045749,0.683793,0.389789,0.016787,0.503695
2,0.226428,0.268764,0.694262,0.622335,0.063843,0.122683,0.815625,0.584542,0.032594,0.589775,0.764350,0.650973,0.565705,0.691784,0.265223,0.739031,0.560394,0.334802,0.517694,0.646110
3,0.362748,0.495430,0.113876,0.594149,0.612522,0.625204,0.864050,0.260279,0.528873,0.168043,0.715929,0.677014,0.175735,0.632370,0.926715,0.085675,0.120525,0.141746,0.771144,0.489660
4,0.033415,0.340433,0.464971,0.363737,0.025815,0.434129,0.415163,0.892210,0.381701,0.415264,0.790801,0.696930,0.819751,0.944029,0.869965,0.041723,0.819140,0.676051,0.109349,0.872947

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [105]:
columns = df.columns
print (columns)
for col in columns:
    print (df[col].median())
  
medianas = df.loc[:, [df[col].median() for col in df.columns if df[col].median() < 0.48]]
df.loc[:, ]

print (medianas)

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19'],
      dtype='object')
0.5183927088531357
0.4982976284251167
0.47617375620406
0.6177974469785128
0.5443924803856541
0.6525702257070289
0.5895587762839766
0.6525833914513712
0.4841639880065958
0.4561419452336911
0.5294121425646423
0.5175904648111134
0.45088123042636974
0.6935141238122557
0.4326206030433662
0.5742865070877934
0.527874493149453
0.47384343112174854
0.5370667066122712
0.5563000721000172

KeyError: "None of [Float64Index([   0.47617375620406,  0.4561419452336911, 0.45088123042636974,\n               0.4326206030433662, 0.47384343112174854],\n             dtype='float64')] are in the [columns]"

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [107]:
df["20"] = df["19"]-0.1
display(df.head(10))

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.276827,0.260054,0.942397,0.113187,0.781355,0.475740,0.152061,0.250324,0.147078,0.162984,...,0.509619,0.593212,0.911839,0.257645,0.386457,0.696932,0.069162,0.952291,0.286542,0.186542
1,0.995885,0.158381,0.244274,0.962163,0.651900,0.930665,0.577190,0.087914,0.960261,0.580840,...,0.661459,0.674085,0.049326,0.785803,0.315645,0.495355,0.232135,0.549324,0.572232,0.472232
2,0.641917,0.821055,0.392437,0.782617,0.510762,0.428320,0.017324,0.680720,0.340412,0.462513,...,0.251949,0.032847,0.995700,0.816563,0.735692,0.435998,0.430411,0.531757,0.489528,0.389528
3,0.806532,0.569258,0.148175,0.809987,0.459632,0.735762,0.730664,0.934502,0.080322,0.763502,...,0.027637,0.409665,0.942846,0.133256,0.157158,0.929446,0.402791,0.685976,0.246594,0.146594
4,0.311185,0.501165,0.365979,0.782807,0.776795,0.797199,0.791946,0.847157,0.771811,0.233944,...,0.053030,0.208551,0.824354,0.588567,0.604341,0.232964,0.229109,0.022881,0.479022,0.379022
0,0.734751,0.195362,0.734309,0.598184,0.763433,0.263434,0.868066,0.058092,0.753502,0.587513,...,0.178356,0.182922,0.147631,0.391188,0.816049,0.749068,0.293260,0.937828,0.880858,0.780858
1,0.772607,0.445391,0.249642,0.787922,0.598583,0.827238,0.624126,0.601524,0.688753,0.338870,...,0.471474,0.267443,0.453351,0.800716,0.045749,0.683793,0.389789,0.016787,0.503695,0.403695
2,0.226428,0.268764,0.694262,0.622335,0.063843,0.122683,0.815625,0.584542,0.032594,0.589775,...,0.650973,0.565705,0.691784,0.265223,0.739031,0.560394,0.334802,0.517694,0.646110,0.546110
3,0.362748,0.495430,0.113876,0.594149,0.612522,0.625204,0.864050,0.260279,0.528873,0.168043,...,0.677014,0.175735,0.632370,0.926715,0.085675,0.120525,0.141746,0.771144,0.489660,0.389660
4,0.033415,0.340433,0.464971,0.363737,0.025815,0.434129,0.415163,0.892210,0.381701,0.415264,...,0.696930,0.819751,0.944029,0.869965,0.041723,0.819140,0.676051,0.109349,0.872947,0.772947

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [144]:
df1 = df.values

array([[0.27682695, 0.26005391, 0.942397  , ..., 0.95229148, 0.28654193,
        0.18654193],
       [0.99588484, 0.15838114, 0.24427361, ..., 0.54932364, 0.57223234,
        0.47223234],
       [0.64191662, 0.82105532, 0.39243713, ..., 0.53175724, 0.48952801,
        0.38952801],
       ...,
       [0.41375213, 0.69305179, 0.7897963 , ..., 0.79783604, 0.19759168,
        0.09759168],
       [0.72800063, 0.34815596, 0.9357869 , ..., 0.93154222, 0.44812438,
        0.34812438],
       [0.13494239, 0.87593106, 0.27350466, ..., 0.84781843, 0.58831904,
        0.48831904]])